#!/usr/bin/env bash

make_crx() (
    cd extension

    jshint *.js

    7z a ../builds/autopark.crx \
        manifest.json \
        background.js \
        options.html \
        options.js \
        ;

    cd ..
)

make_zip() (
    zip -r builds/autopark.zip extension
)

mkdir -p builds
make_crx
make_zip
