#!/usr/bin/env bash

set -e -x

FILES="
background.js
manifest.json
options.html
options.js
"

make_crx() (
    7z a builds/autopark.crx $FILES
)

make_zip() (
    zip builds/autopark.zip $FILES
)

mkdir -p builds
jshint *.js
make_crx
make_zip
